export const plantLabels: Record<string, string> = {
  Tomato: 'Tomate',
  Lettuce: 'Alface',
  Carrot: 'Cenoura',
  Kale: 'Couve',
  Corn: 'Milho',
  Beans: 'Feijão',
  Zucchini: 'Abobrinha',
  Cucumber: 'Pepino',
  Potato: 'Batata',
  Radish: 'Rabanete',
  Beetroot: 'Beterraba',
  'Bell Pepper': 'Pimentão',
  Eggplant: 'Berinjela',
  Spinach: 'Espinafre',
  Basil: 'Manjericão',
  Parsley: 'Salsinha',
  Chives: 'Cebolinha',
  Chicory: 'Chicória',
  Pumpkin: 'Abóbora',
  Garlic: 'Alho',
  Onion: 'Cebola',
  Ginger: 'Gengibre',
  Rosemary: 'Alecrim',
  Strawberry: 'Morango',
  Mint: 'Hortelã',
}
