import { ImageSourcePropType } from 'react-native'

export const plantImages: Record<string, ImageSourcePropType> = {
  Tomato: require('./tomato.jpg'),
  Lettuce: require('./lettuce.jpg'),
  Carrot: require('./carrot.jpg'),
  Kale: require('./kale.jpg'),
  Corn: require('./corn-cob.jpg'),
  Beans: require('./beans.jpg'),
  Zucchini: require('./zucchini.jpg'),
  Cucumber: require('./cucumber.jpg'),
  Potato: require('./potato.jpg'),
  Radish: require('./radish.jpg'),
  Beetroot: require('./beetroot.jpg'),
  'Bell Pepper': require('./bell_pepper.jpg'),
  Eggplant: require('./eggplant.jpg'),
  Spinach: require('./spinach.jpg'),
  Basil: require('./basil.jpg'),
  Parsley: require('./parsley.jpg'),
  Chives: require('./chives.jpg'),
  Chicory: require('./chicory.jpg'),
  Pumpkin: require('./pumpkin.jpg'),
  Garlic: require('./garlic.jpg'),
  Onion: require('./onion.jpg'),
  Ginger: require('./ginger.jpg'),
  Rosemary: require('./rosemary.jpg'),
  Strawberry: require('./strawberry.jpg'),
  Mint: require('./mint.jpg'),
}
